// <auto-generated />
namespace InsuranceBroker.Model.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BrokerTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BrokerTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201303282035487_BrokerTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
